# Generated by Django 3.0.3 on 2020-03-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_react', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
