# Generated by Django 3.0.3 on 2020-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours', '0003_auto_20200406_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(default='General', max_length=1000, verbose_name='topic'),
        ),
    ]
