# Generated by Django 3.0.3 on 2020-03-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.TextField(default='CSE442', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='Matthew Hertz', verbose_name='Name'),
        ),
    ]
