# Generated by Django 3.0.3 on 2020-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200323_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='listcourses',
            field=models.TextField(default='', verbose_name='listcourses'),
        ),
    ]
