# Generated by Django 3.0.3 on 2020-02-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('instructor', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
