# Generated by Django 3.0.3 on 2020-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='instructor',
            field=models.BooleanField(default=True, max_length=300),
            preserve_default=False,
        ),
    ]
